import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import { fromStoryboardSpans, fromTraceSpans } from '../dist/trace-spans.js'

const fixture = (name) => JSON.parse(readFileSync(new URL(`./fixtures/${name}.json`, import.meta.url), 'utf8'))

test('ChatGPT fleet OTLP export projects recorded span IDs and content into one session', () => {
  const spans = fixture('chatgpt-fleet-spans') // generated by tangle-tools/chatgpt-fleet/otlp_export.py
  const record = fromTraceSpans(spans, { recordId: 'chatgpt-review', title: 'Fleet review' })
  assert.equal(record.idScheme, 'trace-span.v1')
  assert.equal(record.nodes.length, 1)
  assert.equal(record.nodes[0].nativeSessionId, 'fixture-chatgpt-one')
  assert.equal(record.nodes[0].parent, null)
  assert.equal(record.events.length, spans.length)
  assert.deepEqual(record.events.map((event) => event.detail.spanId), spans.map((span) => span.span_id))
  assert.equal(record.events.find((event) => event.label === 'user.prompt').detail.publicText, 'Summarize the checked result.')
  assert.equal(record.events.find((event) => event.kind === 'trace-tool').detail.toolNames[0], 'GitHub.read_file')
  assert.equal(record.coverage.completeOriginalCapture, false)
  assert.deepEqual(record.coverage.gaps, [])
})

test('span projection records missing parents and never joins by matching names or times', () => {
  const spans = fixture('chatgpt-fleet-spans')
  const broken = [{ ...spans[0], attributes: { ...spans[0].attributes, 'tangle.sessionId': 'one' } },
    { ...spans[1], parent_span_id: 'missing', attributes: { ...spans[1].attributes, 'tangle.sessionId': 'two' } }]
  const record = fromTraceSpans(broken, { recordId: 'partial', title: 'Partial' })
  assert.equal(record.nodes[0].nativeSessionId, undefined)
  assert.equal(record.nodes[0].capture.status, 'lossy')
  assert.deepEqual(record.coverage.gaps.map((gap) => gap.code), ['session-id-conflict', 'parent-span-unresolved'])
  assert.equal(record.events[1].detail.parentSpanId, 'missing')
  assert.equal(record.nodes[0].parent, null)
})

test('storyboard Span[] retains its IDs, content and measured usage in the same record model', () => {
  const spans = fixture('storyboard-spans')
  const record = fromStoryboardSpans(spans, { recordId: 'storyboard-review', title: 'Storyboard review' })
  assert.equal(record.idScheme, 'storyboard-span.v1')
  assert.equal(record.nodes.length, 1)
  assert.equal(record.events.find((event) => event.kind === 'trace-llm').detail.spanId, 'model-1')
  assert.equal(record.events.find((event) => event.kind === 'trace-llm').detail.usage.input, 7)
  assert.match(record.events.find((event) => event.kind === 'trace-llm').detail.publicText, /The result is checked/u)
  assert.equal(record.events.find((event) => event.kind === 'trace-tool').detail.toolCallId, 'tool-1')
  assert.deepEqual(record.coverage.gaps, [])
})
